### PR TITLE
Pull request to merge Desenv branch to Master on FutProjects - Part 3

### PR DESCRIPTION
**Pull request by Ma145**
Pull request to end FutProjects - Part 3.

### CODE REVIEW

**Comment by Ma145** [comment]
Pull request closed to resolve conflicts.

**Review by vgenerato — APPROVED** [review]
Changes reviewed and approved.

**Comment by enzomoralesl** [comment]
Files changed (76) - temporary files removed.
Approved after review.

**Review by enzomoralesl — APPROVED** [review]
Files reviewed: 76.
Approved after review.

**Review by Vitor-soares-silva — APPROVED** [review]
Approved after review.

**Comment by Ma145** [comment]
Thanks for all the reviews. The branch was merged.

**Pull request merged**
